### ISSUE TITLE
URL malformed in browser

### ISSUE THREAD

**Issue by cartpauj** [th3james/nova-open-on-github#3]
When opening a file it opens in Chrome like so:
`https://github.com///username@github.com/companyname/project/blob/develop/file.php`

Instead of the expected:
`https://github.com/companyname/project/blob/develop/file.php`

As of:
Nova 11.6

**Comment by th3james** [comment]
Hi @cartpauj, thanks for reporting the issue. To help me fix this, could you let me know what the return value of the following command looks like inside the repo you're having issues with?
```sh
git config --get remote.origin.url
```
Obviously, feel free to obfuscate the particular values for your repo

**Comment by cartpauj** [comment]
@th3james 
`https://user@github.com/companyname/project.git`

**Comment by th3james** [comment]
Thanks for the additional detail, I've fixed this and published version 2.1
https://github.com/th3james/nova-open-on-github/commit/e4b9ce367798b37715f4f191471b0ce976e2b9c5

Please confirm if this fixes the issue for you

**Comment by cartpauj** [comment]
The repo from before was cloned using HTTPS, I have another with SSH which is also failing (even after the update)
`https://github.com/ssh://git@github.com/company/project/blob/develop/app/lib/file.php`

Command output:
`ssh://git@github.com/company/project.git`

**Comment by th3james** [comment]
Thanks again, version 2.2 published with a fix

**Comment by cartpauj** [comment]
Thanks, unfortunately it's still not working after updating to 2.2

I get the following now:
`https://github.com/ssh://git@github.com/company/project/blob/main/CHANGELOG.md`

**Comment by th3james** [comment]
Sorry about that, 2.3 is now live with actual fix
https://github.com/th3james/nova-open-on-github/commit/15bfc80787e915db77d0c832fd4340619daa686d

**Comment by cartpauj** [comment]
Works now, thanks!
